"""Generate the YACP logo assets from one shared geometric definition."""

import math
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
LOGO_SIZE = 120
SUPERSAMPLE = 8


def _scaled(value: int, scale: int) -> int:
    return value * scale


def _arc_points(
    center_x: float,
    center_y: float,
    radius: float,
    start_degrees: float,
    end_degrees: float,
    steps: int = 24,
) -> list[tuple[float, float]]:
    points = []
    for step in range(1, steps + 1):
        angle = math.radians(start_degrees + (end_degrees - start_degrees) * step / steps)
        points.append((center_x + radius * math.cos(angle), center_y + radius * math.sin(angle)))
    return points


def _reading_path_points() -> list[tuple[float, float]]:
    points = [(30.0, 24.0), (82.0, 24.0)]
    points.extend(_arc_points(82.0, 35.0, 11.0, -90.0, 90.0))
    points.append((30.0, 46.0))
    points.extend(_arc_points(30.0, 57.0, 11.0, -90.0, -270.0))
    points.append((82.0, 68.0))
    points.extend(_arc_points(82.0, 79.0, 11.0, -90.0, 90.0))
    points.append((30.0, 90.0))
    points.extend(_arc_points(30.0, 96.0, 6.0, -90.0, -180.0, steps=12))
    return points


def _draw_logo(image: Image.Image, scale: int) -> None:
    draw = ImageDraw.Draw(image)
    black = (0, 0, 0, 255)
    stroke_width = _scaled(11, scale)

    path_points = [
        (round(_scaled(x, scale)), round(_scaled(y, scale))) for x, y in _reading_path_points()
    ]
    draw.line(path_points, fill=black, width=stroke_width, joint="curve")
    cap_radius = stroke_width // 2
    for x, y in (path_points[0], path_points[-1]):
        draw.ellipse((x - cap_radius, y - cap_radius, x + cap_radius, y + cap_radius), fill=black)

    draw.polygon(
        [
            (_scaled(75, scale), _scaled(84, scale)),
            (_scaled(91, scale), _scaled(84, scale)),
            (_scaled(91, scale), _scaled(108, scale)),
            (_scaled(83, scale), _scaled(100, scale)),
            (_scaled(75, scale), _scaled(108, scale)),
        ],
        fill=black,
    )


def _render_rgba(size: int) -> Image.Image:
    working_size = LOGO_SIZE * SUPERSAMPLE
    image = Image.new("RGBA", (working_size, working_size), (255, 255, 255, 0))
    _draw_logo(image, SUPERSAMPLE)
    return image.resize((size, size), Image.Resampling.LANCZOS)


def _write_if_changed(path: Path, data: bytes) -> None:
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def _save_png(path: Path, size: int, *, opaque_white: bool = False) -> None:
    image = _render_rgba(size)
    if opaque_white:
        background = Image.new("RGBA", image.size, (255, 255, 255, 255))
        background.alpha_composite(image)
        image = background
    from io import BytesIO

    output = BytesIO()
    image.save(output, format="PNG", optimize=True)
    _write_if_changed(path, output.getvalue())


def _svg() -> str:
    return """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" role="img">
  <title>YACP continuous reading path</title>
  <desc>A rounded reading path crossing four lines and ending as a bookmark.</desc>
  <path d="M30 24h52a11 11 0 0 1 0 22H30a11 11 0 0 0 0 22h52a11 11 0 0 1 0 22H30a6 6 0 0 0-6 6"
        fill="none" stroke="#000" stroke-width="11" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M75 84h16v24l-8-8-8 8z" fill="#000"/>
</svg>
"""


def _firmware_header() -> str:
    image = Image.new("RGBA", (LOGO_SIZE * SUPERSAMPLE, LOGO_SIZE * SUPERSAMPLE), (255, 255, 255, 255))
    _draw_logo(image, SUPERSAMPLE)
    image = image.resize((LOGO_SIZE, LOGO_SIZE), Image.Resampling.LANCZOS).convert("L")
    image = image.point(lambda value: 255 if value >= 128 else 0)

    # GfxRenderer rotates coordinates but not bitmap bits in portrait mode.
    # Match the existing icon pipeline by storing the boot logo pre-rotated.
    image = image.rotate(90, expand=True)

    packed: list[int] = []
    pixels = image.load()
    for y in range(LOGO_SIZE):
        for x in range(0, LOGO_SIZE, 8):
            value = 0
            for bit in range(8):
                if pixels[x + bit, y] >= 128:
                    value |= 1 << (7 - bit)
            packed.append(value)

    rows = []
    for offset in range(0, len(packed), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in packed[offset : offset + 16]) + ",")

    return (
        "#pragma once\n"
        "#include <cstdint>\n\n"
        "// Generated by scripts/build_yacp_logo.py. 120x120, 1 bit per pixel.\n"
        "inline constexpr uint8_t Logo120[] = {\n"
        + "\n".join(rows)
        + "\n};\n"
        'static_assert(sizeof(Logo120) == 1800, "Logo120 must be exactly 120x120 / 8 bytes");\n'
    )


def main() -> None:
    _write_if_changed(ROOT / "assets" / "brand" / "yacp-logo.svg", _svg().encode("utf-8"))
    _save_png(ROOT / "docs" / "images" / "yacp" / "logo.png", 512, opaque_white=True)
    _save_png(ROOT / "web" / "assets" / "logo.png", 128)
    _write_if_changed(ROOT / "src" / "images" / "Logo120.h", _firmware_header().encode("utf-8"))
    print("Generated YACP logo assets")


if __name__ == "__main__":
    main()
